web:
  build: .
  ports:
    - "7777:7777"
  links:
    - redis
  volumes:
    - /path/to/config.js:/opt/haste/config.js
  environment:
    VIRTUAL_HOST: my.domain.tld
redis:
  image: redis:3.0
  volumes:
    - /path/to/redis/data/directory:/data
  command: redis-server --appendonly yes
nginx:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
